# File: pnpm-workspace.yaml

packages:
  - .
  - web

allowBuilds:
  '@discordjs/opus': true
  '@prisma/engines': true
  esbuild: true
  prisma: true

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@prisma/engines'
  - esbuild
  - prisma
