# File: .github/workflows/type-check.yml

name: Type Check

on: [push, pull_request]

jobs:
  build:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Enable Corepack
        run: corepack enable

      - name: Install package manager
        run: corepack install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm prisma generate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/isobel

      - name: Run type check
        run: pnpm run typecheck
